const {
  PORT = 3001,
  DEBUG = 'false',
  APIHOLIDAYS_HOST,
  CIRCUIT_BREAKER_APIHOLIDAYS_THRESHOLD_TIMEOUT = 3000,
  CIRCUIT_BREAKER_APIHOLIDAYS_THRESHOLD_PERCENTAGE,
  CIRCUIT_BREAKER_APIHOLIDAYS_RESET_TIMEOUT,
  CIRCUIT_BREAKER_APIHOLIDAYS_VOLUME_THRESHOLD = 1,
  CIRCUIT_BREAKER_APIHOLIDAYS_ENABLED = 'false'
} = process.env;

module.exports = {
  PORT,
  DEBUG: JSON.parse(DEBUG),
  APIHOLIDAYS_HOST,
  CIRCUIT_BREAKER: {
    APIHOLIDAYS: {
      timeout: parseInt(CIRCUIT_BREAKER_APIHOLIDAYS_THRESHOLD_TIMEOUT),
      errorThresholdPercentage: parseInt(CIRCUIT_BREAKER_APIHOLIDAYS_THRESHOLD_PERCENTAGE),
      resetTimeout: parseInt(CIRCUIT_BREAKER_APIHOLIDAYS_RESET_TIMEOUT),
      volumeThreshold: parseInt(CIRCUIT_BREAKER_APIHOLIDAYS_VOLUME_THRESHOLD),
      enabled: JSON.parse(CIRCUIT_BREAKER_APIHOLIDAYS_ENABLED)
    }
  }
};